presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.15.0
          command:
            - "pre-commit"
            - "run"
            - "--all-files"

  - name: thoth-pytest-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pytest
    spec:
      containers:
        - image: quay.io/goern/thoth-pytest:v0.13.0-dev
          command:
            - "/bin/run-pytest"

  - name: thoth-mypy-py38
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/mypy
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-pytest-ubi8-py38:v0.12.5
          command:
            - "/usr/local/bin/mypy"
            - "."
            - "--ignore-missing-imports"
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"
