- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "metrics-exporter"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
