- project:
    check:
      jobs:
        - linters
        - thoth-tests
    gate:
      jobs:
        - noop
    release:
      jobs:
        - upload-test-pypi

- job:
    name: thoth-tests
    parent: base-thoth-openshift
    run: thoth-tests.yaml
    nodeset: {nodes: [{name: namespace, label: thoth-engint}]}
    vars:
      base_image: "python:3.6"
