---
- project:
    check:
      jobs:
        - pipenv-setuppy-test
        - linters
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - linters

- job:
    name: pipenv-setuppy-test
    parent: base-openshift-pod
    run: test.yaml
    nodeset: openpaas-thoth-python-36-centos7-pod
