- project:
    check:
      jobs:
        - openshift-test
        - linters:
            vars:
              linters:
                - coala
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

- job:
    name: openshift-test
    parent: base-thoth-openshift
    run: test.yaml
    nodeset: {nodes: [{name: namespace, label: thoth-engint}]}
    vars:
      base_image: "python:3.6"
