---
- project:
    check:
      jobs:
        - demo-pod
    gate:
      jobs:
        - linters
    release:
      jobs:
        - upload-test-pypi
    kebechet-auto-gate:
      jobs:
        - linters

- job:
    name: demo-pod
    run: test.yaml
    nodeset: thoth-python-36-centos7-pod
