---
- project:
    check:
      jobs:
        - linters
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - linters

- job:
    name: demo-pod
    parent: base-openshift-pod
    run: test.yaml
    nodeset: openpaas-fedora