---
- project:
    check:
      jobs:
        - linters-pod
        - demo-pod
    gate:
      jobs:
        - linters
    release:
      jobs:
        - upload-test-pypi
    kebechet-auto-gate:
      jobs:
        - linters

- job:
    name: demo-pod
    parent: base-openshift-pod
    run: test.yaml
    nodeset: openpaas-thoth-python-36-centos7-pod

- job:
    name: linters-pod
    parent: base-openshift-pod
    run: linters.yaml
    nodeset: openpaas-thoth-python-36-centos7-pod
