- project:
    check:
      queue: "thoth-station/core"
      jobs:
        # FIXME for bots        - "dco-license"
        # - "thoth-github-wip"
        - "thoth-coala"
        - "thoth-pytest"
        - "thoth-pytest-py37"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "metrics-exporter"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
