- hosts: pod
  tasks:
    - command: pipenv run pyton setup.py test
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - command: coala --ci
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - command: python foo.py
      args:
        chdir: "{{ zuul.project.src_dir }}"
